/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package riego_guidb_aqe2;

import com.mysql.jdbc.*;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Gerome Riego
 */
public class Database extends javax.swing.JFrame {
    private static java.sql.Statement se;
    private static ResultSet rs;
    private static Connection con;
    private static PreparedStatement ps;
    int loopcount = 1;    
    /**
     * Creates new form Database
     * @param con
     * @param dbname
     */
    public Database(Connection con) {
        initComponents();
        Database.con = con;
        getData();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        jButton7 = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jSeparator1 = new javax.swing.JSeparator();
        jLabel2 = new javax.swing.JLabel();
        jTextField1 = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jTextField3 = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        jTextField4 = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jRadioButton1 = new javax.swing.JRadioButton();
        jRadioButton2 = new javax.swing.JRadioButton();
        jButton4 = new javax.swing.JButton();
        jButton5 = new javax.swing.JButton();
        jLabel7 = new javax.swing.JLabel();
        jButton6 = new javax.swing.JButton();
        jLabel8 = new javax.swing.JLabel();
        jButton8 = new javax.swing.JButton();
        jButton9 = new javax.swing.JButton();
        jButton10 = new javax.swing.JButton();
        jButton11 = new javax.swing.JButton();
        jTextField2 = new javax.swing.JTextField();
        jButton12 = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();

        jButton7.setText("<");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setPreferredSize(new java.awt.Dimension(946, 635));
        setResizable(false);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosing(java.awt.event.WindowEvent evt) {
                formWindowClosing(evt);
            }
        });
        getContentPane().setLayout(null);

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Name", "Gender", "Contact No.", "Address", "ID"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.Integer.class, java.lang.String.class, java.lang.String.class
            };
            boolean[] canEdit = new boolean [] {
                true, false, false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(jTable1);
        if (jTable1.getColumnModel().getColumnCount() > 0) {
            jTable1.getColumnModel().getColumn(0).setResizable(false);
            jTable1.getColumnModel().getColumn(1).setResizable(false);
            jTable1.getColumnModel().getColumn(3).setResizable(false);
            jTable1.getColumnModel().getColumn(4).setResizable(false);
        }

        getContentPane().add(jScrollPane1);
        jScrollPane1.setBounds(10, 200, 910, 350);
        getContentPane().add(jSeparator1);
        jSeparator1.setBounds(0, 40, 930, 20);

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel2.setText("Database");
        getContentPane().add(jLabel2);
        jLabel2.setBounds(410, 0, 120, 50);
        getContentPane().add(jTextField1);
        jTextField1.setBounds(110, 60, 110, 22);

        jLabel3.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel3.setText("Name:");
        getContentPane().add(jLabel3);
        jLabel3.setBounds(60, 60, 41, 20);

        jLabel4.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel4.setText("Gender:");
        getContentPane().add(jLabel4);
        jLabel4.setBounds(51, 90, 50, 20);
        getContentPane().add(jTextField3);
        jTextField3.setBounds(110, 120, 110, 22);

        jLabel5.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel5.setText("Contact No.:");
        getContentPane().add(jLabel5);
        jLabel5.setBounds(21, 120, 80, 20);
        getContentPane().add(jTextField4);
        jTextField4.setBounds(110, 150, 110, 22);

        jLabel6.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel6.setText("Address:");
        getContentPane().add(jLabel6);
        jLabel6.setBounds(41, 150, 60, 20);

        jButton1.setText("Submit");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1);
        jButton1.setBounds(240, 60, 80, 25);

        jButton2.setText("Delete");
        jButton2.setActionCommand("Delete");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton2);
        jButton2.setBounds(240, 140, 80, 25);

        jButton3.setText("Update");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton3);
        jButton3.setBounds(240, 100, 80, 25);

        buttonGroup1.add(jRadioButton1);
        jRadioButton1.setFont(new java.awt.Font("Tahoma", 0, 10)); // NOI18N
        jRadioButton1.setSelected(true);
        jRadioButton1.setText("Male");
        getContentPane().add(jRadioButton1);
        jRadioButton1.setBounds(110, 90, 60, 25);

        buttonGroup1.add(jRadioButton2);
        jRadioButton2.setFont(new java.awt.Font("Tahoma", 0, 10)); // NOI18N
        jRadioButton2.setText("Female");
        getContentPane().add(jRadioButton2);
        jRadioButton2.setBounds(171, 90, 60, 25);

        jButton4.setText("Get Row Count");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton4);
        jButton4.setBounds(340, 70, 120, 25);

        jButton5.setText("<html> Get Column<br>        Count </html>");
        jButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton5ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton5);
        jButton5.setBounds(340, 110, 120, 50);

        jLabel7.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel7.setText("1");
        getContentPane().add(jLabel7);
        jLabel7.setBounds(530, 90, 10, 20);

        jButton6.setText("<");
        jButton6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton6ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton6);
        jButton6.setBounds(470, 80, 50, 40);

        jLabel8.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel8.setText("Loop Count:");
        getContentPane().add(jLabel8);
        jLabel8.setBounds(480, 60, 100, 20);

        jButton8.setText(">");
        jButton8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton8ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton8);
        jButton8.setBounds(550, 80, 50, 40);

        jButton9.setText("Submit with loop");
        jButton9.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton9ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton9);
        jButton9.setBounds(470, 130, 129, 25);

        jButton10.setText("<html>Add Generic <br>Data</html>");
        jButton10.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton10ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton10);
        jButton10.setBounds(610, 70, 100, 50);

        jButton11.setText("Reset Table");
        jButton11.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton11ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton11);
        jButton11.setBounds(610, 130, 100, 25);

        jTextField2.setEditable(false);
        getContentPane().add(jTextField2);
        jTextField2.setBounds(720, 140, 110, 22);

        jButton12.setText("<html>\nGet Selected<br>\nCell Value\n</html>");
        jButton12.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton12ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton12);
        jButton12.setBounds(720, 80, 110, 50);

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/riego_guidb_aqe2/istockphoto-1138395421-612x612.jpg"))); // NOI18N
        getContentPane().add(jLabel1);
        jLabel1.setBounds(0, 0, 950, 620);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        //Submit button
        try {
            DefaultTableModel mytable = (DefaultTableModel) jTable1.getModel();
            String name = jTextField1.getText();
            String gender = null;
            if (jRadioButton1.isSelected()){gender = "Male";}
            if (jRadioButton2.isSelected()){gender = "Female";}
            int contact = Integer.parseInt(jTextField3.getText());
            String address = jTextField4.getText();
            String query = "INSERT INTO `information` (`Name`, `Gender`, `Contact No.`, `Address`, `ID`) VALUES (?, ?, ?, ?, null)";
            ps = con.prepareStatement(query);
            ps.setString(1, name);
            ps.setString(2, gender);
            ps.setInt(3, contact);
            ps.setString(4, address);
            ps.executeUpdate();
            mytable.addRow(new Object[]{
                name,
                gender,
                contact,
                address,
                (mytable.getRowCount() + 1)});
        } catch (SQLException | NumberFormatException ex) {
            System.out.println("Error" + ex);
            JOptionPane.showMessageDialog(this, "Please input a number in Contact No.");
        }
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
       //Update Button
        try {
            if (jTable1.getSelectedRow() < 0) {
                JOptionPane.showMessageDialog(this, "Please select the row you want to update");
            } else {
                DefaultTableModel mytable = (DefaultTableModel) jTable1.getModel();
                String name = jTextField1.getText();
                String gender = null;
                if (jRadioButton1.isSelected()){gender = "Male";}
                if (jRadioButton2.isSelected()){gender = "Female";}
                int contact = Integer.parseInt(jTextField3.getText());
                String address = jTextField4.getText();
                int row = jTable1.getSelectedRow();
                System.out.println(row);
                String query = "Update `information` Set `Name` = ?, `Gender` = ?, `Contact No.` = ?, `Address` = ? WHERE ID = ?;";
                ps = con.prepareStatement(query);
                ps.setString(1, name);
                ps.setString(2, gender);
                ps.setInt(3, contact);
                ps.setString(4, address);
                ps.setInt(5, (row + 1));
                ps.executeUpdate();
                mytable.setValueAt(name, row, 0);
                mytable.setValueAt(gender, row, 1);
                mytable.setValueAt(contact, row, 2);
                mytable.setValueAt(address, row, 3);
            }
        } catch (SQLException | NumberFormatException ex) {
            System.out.println("Error" + ex);
            JOptionPane.showMessageDialog(this, "Please input a number in Contact No.");
        }
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        //Delete Button
                try {
            if (jTable1.getSelectedRow() < 0) {
                JOptionPane.showMessageDialog(this, "Please select the row you want to delete");
            } else {
                DefaultTableModel mytable = (DefaultTableModel) jTable1.getModel();
                int row = jTable1.getSelectedRow();
                System.out.println(row);
                String query = "DELETE FROM `information` WHERE `ID` = ?;";
                ps = con.prepareStatement(query);
                ps.setInt(1, (row + 1));
                ps.executeUpdate();
                mytable.removeRow(row);
            }
        } catch (SQLException ex) {
            System.out.println("Error" + ex);
        }
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        // Get row count button
        DefaultTableModel mytable = (DefaultTableModel) jTable1.getModel();
        JOptionPane.showMessageDialog(this,
                "There are " + mytable.getRowCount() + " rows",
                "Number of Rows:",
                JOptionPane.INFORMATION_MESSAGE); 
    }//GEN-LAST:event_jButton4ActionPerformed

    private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5ActionPerformed
        // Get column count button
        DefaultTableModel mytable = (DefaultTableModel) jTable1.getModel();
        JOptionPane.showMessageDialog(this,
                "There are " + mytable.getColumnCount() + " columns",
                "Number of Columns:",
                JOptionPane.INFORMATION_MESSAGE);
    }//GEN-LAST:event_jButton5ActionPerformed

    private void jButton6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton6ActionPerformed
        // back loop
        if (loopcount == 1){
            JOptionPane.showMessageDialog(this,
                    "You can't go any lower than 1",
                    "Minimum reached!",
                    JOptionPane.WARNING_MESSAGE);
        } else{
            loopcount -= 1;
            jLabel7.setText(String.valueOf(loopcount));
        }
    }//GEN-LAST:event_jButton6ActionPerformed

    private void jButton8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton8ActionPerformed
        // front loop
        loopcount += 1;
        jLabel7.setText(String.valueOf(loopcount));
    }//GEN-LAST:event_jButton8ActionPerformed

    private void jButton9ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton9ActionPerformed
        //submit with loop
        try {
            DefaultTableModel mytable = (DefaultTableModel) jTable1.getModel();
            String name = jTextField1.getText();
            String gender = null;
            if (jRadioButton1.isSelected()){gender = "Male";}
            if (jRadioButton2.isSelected()){gender = "Female";}
            int contact = Integer.parseInt(jTextField3.getText());
            String address = jTextField4.getText();
            for (int i = 1; i <= loopcount; i++ ) {
                String query = "INSERT INTO `information` (`Name`, `Gender`, `Contact No.`, `Address`, `ID`) VALUES (?, ?, ?, ?, null)";
                ps = con.prepareStatement(query);
                ps.setString(1, name);
                ps.setString(2, gender);
                ps.setInt(3, contact);
                ps.setString(4, address);
                ps.executeUpdate();
                mytable.addRow(new Object[]{
                    name,
                    gender,
                    contact,
                    address,
                    (mytable.getRowCount() + 1)});
            }
        } catch (SQLException | NumberFormatException ex) {
            System.out.println("Error" + ex);
            JOptionPane.showMessageDialog(this, "Please input a number in Contact No.");
        }
    }//GEN-LAST:event_jButton9ActionPerformed

    private void jButton11ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton11ActionPerformed
        // reset table
        int resettable = JOptionPane.showConfirmDialog(this, "Are you sure you want to RESET TABLE??", "Reset Table?",
        JOptionPane.YES_NO_OPTION, JOptionPane.QUESTION_MESSAGE);
        if (resettable == JOptionPane.YES_OPTION) {
            try {
                String query = "TRUNCATE TABLE `information`;";
                se = con.prepareStatement(query);
                se.executeUpdate(query);
                DefaultTableModel mytable = (DefaultTableModel) jTable1.getModel();
                mytable.setNumRows(0);
            } catch (SQLException ex) {
                System.out.println("Error" + ex);
            }
        }
    }//GEN-LAST:event_jButton11ActionPerformed

    private void jButton10ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton10ActionPerformed
        // add generic data
        try {
            DefaultTableModel mytable = (DefaultTableModel) jTable1.getModel();
            String name = "Gerome";
            String gender = null;
            if (jRadioButton1.isSelected()){gender = "Male";}
            if (jRadioButton2.isSelected()){gender = "Female";}
            int contact = 0;
            String address = "Earth";
            String query = "INSERT INTO `information` (`Name`, `Gender`, `Contact No.`, `Address`, `ID`) VALUES (?, ?, ?, ?, null)";
            ps = con.prepareStatement(query);
            ps.setString(1, name);
            ps.setString(2, gender);
            ps.setInt(3, contact);
            ps.setString(4, address);
            ps.executeUpdate();
            mytable.addRow(new Object[]{
                name,
                gender,
                contact,
                address,
                (mytable.getRowCount() + 1)});
        } catch (SQLException | NumberFormatException ex) {
            System.out.println("Error" + ex);
            JOptionPane.showMessageDialog(this, "Please input a number in Contact No.");
        }

    }//GEN-LAST:event_jButton10ActionPerformed

    private void formWindowClosing(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowClosing
        // closing confirmation
        this.setDefaultCloseOperation(Database.EXIT_ON_CLOSE );
        int option = JOptionPane.showConfirmDialog
            (this,"Are you sure you want to quit?", "QUIT?",
            JOptionPane.YES_NO_OPTION, JOptionPane.QUESTION_MESSAGE);
        if (option == JOptionPane.NO_OPTION){
            this.setDefaultCloseOperation(Database.DO_NOTHING_ON_CLOSE );
        }
    }//GEN-LAST:event_formWindowClosing

    private void jButton12ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton12ActionPerformed
        //get selected cell value
        int row = jTable1.getSelectedRow();
        int column = jTable1.getSelectedColumn();
        jTextField2.setText(String.valueOf(jTable1.getValueAt(row, column)));
    }//GEN-LAST:event_jButton12ActionPerformed


    public void getData() {
        try {
            String query = "SELECT * FROM `information`;";
            DefaultTableModel mytable = (DefaultTableModel) jTable1.getModel();
            se = con.prepareStatement(query);
            rs = se.executeQuery(query);
            while (rs.next()) {
                String name = rs.getString(1);
                String gender = rs.getString(2);
                int contact = rs.getInt(3);
                String Address = rs.getString(4);
                int Pid = rs.getInt(5);
                System.out.println("Name: " + name + "\t"
                        + "Gender: " + gender + "\t"
                        + "Contact No.: " + contact + "\t"
                        + "Address: " + Address + "\t"
                        + "ID: " + Pid + "\t");
                mytable.addRow(new Object[]{
                    name,
                    gender,
                    contact,
                    Address,
                    Pid});
            }
        } catch (SQLException ex) {
            System.out.println("Error" + ex);
        }
    }
    
    
    
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Database.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Database.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Database.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Database.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
               // new Database(Connection con).setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton10;
    private javax.swing.JButton jButton11;
    private javax.swing.JButton jButton12;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5;
    private javax.swing.JButton jButton6;
    private javax.swing.JButton jButton7;
    private javax.swing.JButton jButton8;
    private javax.swing.JButton jButton9;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JRadioButton jRadioButton1;
    private javax.swing.JRadioButton jRadioButton2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JTable jTable1;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTextField jTextField2;
    private javax.swing.JTextField jTextField3;
    private javax.swing.JTextField jTextField4;
    // End of variables declaration//GEN-END:variables
}
